#!/bin/bash
#---
# name: Install commit-msg hook
# type: session
#---
set -euo pipefail

workspace_root="${DISCOBOT_WORKSPACE:-/home/discobot/workspace}"
git_hooks_dir="$workspace_root/.git/hooks"
commit_msg_hook="$git_hooks_dir/commit-msg"
commit_msg_original="$git_hooks_dir/commit-msg.original"
managed_marker="# discobot:managed-commit-msg"

mkdir -p "$git_hooks_dir"

if [ -f "$commit_msg_hook" ] && ! grep -Fq "$managed_marker" "$commit_msg_hook"; then
	cp "$commit_msg_hook" "$commit_msg_original"
fi

cat >"$commit_msg_hook" <<'EOF'
#!/bin/bash
# Auto-generated by discobot session hook
# Source: .discobot/hooks/07-install-commit-msg-hook.sh
# DO NOT EDIT — regenerated when the session starts
# discobot:managed-commit-msg
set -euo pipefail

msg_file="$1"
subject_limit=50
body_limit=72

if [ ! -f "$msg_file" ]; then
	exit 0
fi

if [ -f "$(dirname "$0")/commit-msg.original" ]; then
	"$(dirname "$0")/commit-msg.original" "$msg_file"
fi

declare -a lines=()
while IFS= read -r line || [ -n "$line" ]; do
	line=${line%$'\r'}
	if [[ "$line" == \#* ]]; then
		continue
	fi
	lines+=("$line")
done <"$msg_file"

while [ ${#lines[@]} -gt 0 ] && [ -z "${lines[${#lines[@]}-1]}" ]; do
	unset 'lines[${#lines[@]}-1]'
done

if [ ${#lines[@]} -eq 0 ]; then
	exit 0
fi

subject="${lines[0]}"
declare -a errors=()

if [ ${#subject} -gt $subject_limit ]; then
	errors+=("- Subject is ${#subject} characters; keep it at ${subject_limit} or fewer.")
fi

if [ ${#lines[@]} -gt 1 ] && [ -n "${lines[1]}" ]; then
	errors+=("- Add a blank line between the subject and the body.")
fi

for ((i = 1; i < ${#lines[@]}; i++)); do
	line="${lines[$i]}"
	if [ -z "$line" ]; then
		continue
	fi

	case "$line" in
		Signed-off-by:*|Co-authored-by:*|Co-Authored-By:*|Reviewed-by:*|Acked-by:*|Tested-by:*|Reported-by:*|Fixes:*|Closes:*|Refs:*)
			continue
			;;
	esac

	if [ ${#line} -gt $body_limit ]; then
		errors+=("- Body line $((i + 1)) is ${#line} characters; wrap body lines at ${body_limit}.")
	fi
done

if [ ${#errors[@]} -gt 0 ]; then
	printf '%s\n' "Commit message does not match the repository style:" >&2
	printf '%s\n' "" >&2
	printf '%s\n' "${errors[@]}" >&2
	printf '%s\n' "" >&2
	printf '%s\n' "Expected format:" >&2
	printf '%s\n' "- Subject line: 50 characters or fewer" >&2
	printf '%s\n' "- Blank line between subject and body" >&2
	printf '%s\n' "- Body lines: 72 characters or fewer" >&2
	exit 1
fi
EOF

chmod 755 "$commit_msg_hook"
